# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160702_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lcat',
            name='variables',
            field=models.ManyToManyField(to='home.Variable'),
        ),
        migrations.AddField(
            model_name='order',
            name='lcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Lcat'),
            preserve_default=False,
        ),
    ]
