# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160702_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccid', models.CharField(blank=True, max_length=100, null=True)),
                ('wrongProduct', models.CharField(blank=True, max_length=10, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('lookingFor', models.CharField(blank=True, max_length=10, null=True)),
                ('issue', models.ManyToManyField(to='home.Variable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Order')),
            ],
        ),
    ]
