# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='lookingFor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
